service: user-events-service

provider:
  name: aws
  runtime: python3.9
  region: us-east-1

  environment:
    TABLE_NAME: users_events
    QUEUE_URL:
      Ref: UserEventsQueue
    EVENT_BUS_NAME: user-events-bus  

  iam:
    role:
      statements:
        # DynamoDB permission
        - Effect: Allow
          Action:
            - dynamodb:UpdateItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/users_events

        # EventBridge permission (restricted to custom bus)
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource:
            - arn:aws:events:${self:provider.region}:${aws:accountId}:event-bus/user-events-bus

package:
  patterns:
    - common/**
    - process_user/**
    - update_user/**

functions:

  updateUser:
    handler: update_user/handler.lambda_handler
    events:
      - httpApi:
          path: /user/{id}
          method: put

  processUserUpdate:
    handler: process_user/handler.lambda_handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - UserEventsQueue
              - Arn
          batchSize: 5

resources:
  Resources:

    #  Custom Event Bus
    UserEventsBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: user-events-bus

    #  SQS Queue
    UserEventsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: UserEventsQueue

    #  EventBridge Rule (uses custom bus)
    UserUpdatedEventRule:
      Type: AWS::Events::Rule
      Properties:
        Name: UserUpdatedToSQS
        EventBusName:
          Ref: UserEventsBus   
        EventPattern:
          source:
            - user.service
          detail-type:
            - UserUpdated
        Targets:
          - Arn:
              Fn::GetAtt:
                - UserEventsQueue
                - Arn
            Id: "UserEventsQueueTarget"

    # DynamoDB Table
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users_events
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH